# Generated by Django 5.0.1 on 2024-01-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_delete_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
    ]
